name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies and build
        run: |
          npm install
          npm run build
          npm run dev

      - name: Clear npm cache
        run: npm cache clean --force
        
      - name: List files in vendor/livewire/livewire/dist
        run: ls -R vendor/livewire/livewire/dist

          
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to match your PHP version
          extensions: mbstring, xml, mysql, bcmath # Add any necessary PHP extensions

      - name: Install Composer dependencies
        run: composer install
      
      - name: Deploy to cPanel via FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "
          set ftp:ssl-allow no;
          mirror --reverse --delete --verbose \
          public/ /home/ducodeep/elhradama01.ducodeverse.com/public/;
          bye;
          " -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
