name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install NPM dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel via FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "
          set ftp:ssl-allow no;
          mirror --reverse --delete --verbose \
          public/ /home/ducodeep/elhradama01.ducodeverse.com/public/;
          bye;
          " -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
