name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASS: ${{ secrets.CPANEL_PASS }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        run: |
          curl -u $CPANEL_USER:$CPANEL_PASS \
          -T public/css/* \
          -T public/js/* \
          /home/ducodeep/elhradama01.ducodeverse.com/public/
